### ISSUE TITLE
Remember the sections and comments that has been read by the user

### ISSUE THREAD

**Issue by odd** [Lundgren/ces#1]
Hello and thanks for a great extension! 

(I want to point out that I use the Chrome plugin from within Brave so my view of how the extension works will be affected by that)

I read the Cornucopia blog at several times through out each day and do a page reload each time I start anew. This extension allows me to keep track of new sections and comments but the problem is that since I do not have time to read the entire page on each visit, only part of the page will have been read by me when I do a reload. Everything present on the page above the comment I'm currently reading can be assumed to have been read, while everything present on the page below the comment I'm currently reading can be assumed to be unread. 
As the extension currently works it seems as it assumes the entire page is read before a reload which leads to repeated reloads marking everything as read.  
Instead this is what I would like:
1. The ability to read any new sections at the bottom of the blog post (written by the blogger)
2. The ability to read any new comments for the topics I have already read
3. The ability to resume reading from the point I left off of earlier (everything below this point should be considered unread, regardless of when it was published)
4. The ability to do repeated reloads without loosing the context for the points above 

Thanks again!
Odd

**Comment by Lundgren** [comment]
Thanks for the suggestion! 

I added a new settings `All comments are marked as read on page load`, if you uncheck that it will change to mark comments as read when you see them in the browser instead of on page load. It will also update the highlight color to a slightly darker nuance so it's visible which comments has been marked as read. 

There's also an existing option for automatically jumping to the first unread paragraph or comment that you might wanna activate so you don't mark comments as read when you go to the top after a reload.

Give it a try and please open another issue or make some comments here if you have additional suggestions on the feature.
